name: mdl-sc-isoform-2025-ms
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  # data
  - anndata
  - edlib
  - h5py
  - leidenalg
  - ncls
  - networkx
  - numba
  - numpy
  - pandas
  - polars
  - pysam
  - python-fastjsonschema
  - python-igraph
  - pyyaml
  - scanpy
  - scikit-learn
  - scipy
  - seaborn
  - sparse
  # visualization
  - matplotlib
  - python-graphviz
  - pygraphviz
  - upsetplot
  # R base and packages
  - r-base
  - r-seurat
  - r-tidyverse 
  - r-dplyr
  - r-ggplot2
  - r-tidyr
  - r-tibble
  - r-matrix
  - r-patchwork
  # mdl code
  - pip:
    - git+https://github.com/MethodsDev/isoscelles.git
    - git+https://github.com/MethodsDev/mdl-core.git
    - git+https://github.com/MethodsDev/callao.git
    - git+https://github.com/MethodsDev/bouncer.git
    - git+https://github.com/MethodsDev/bugzapper.git
    - git+https://github.com/MethodsDev/ITV.git
    - git+https://github.com/RicYaben/UpSetPlot.git@bceb91d7655dd30a189eb58823c9b301a174f35b
    - .
